announcement/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.announcements, name='announcements'),
    path('announcement/<int:announcement_pk>/', views.show_announcement, name='show-announcement'),
    path('add-announcement/', views.add_announcement, name='add-announcement'),
    path('edit-announcement/<int:announcement_pk>/', views.edit_announcement, name='edit-announcement'),
    path('delete-announcement/<int:announcement_pk>/', views.delete_announcement, name='delete-announcement'),
    path('change-sold-status-announcement/<int:announcement_pk>/<str:status>/', views.change_sold_status_announcement, name='change-sold-status-announcement'),
]

sauto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('', include('announcement.urls')),
    path('favorite/', include('favorite.urls')),
    path('profile/', include('userprofile.urls')),
    path('telegrambot/', include('telegrambot.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

announcement/models.py
from django.core.validators import MinValueValidator
from django.utils.translation import gettext_lazy as _
from django.db import models
from seller.models import Seller


class Announcement(models.Model):
    CATEGORIES = (
        (None, 'Не выбрано'),
        (0, 'Прочее'),
        (1, 'Женский гардероб'),
        (2, 'Мужской гардероб'),
        (3, 'Детский гардероб'),
        (4, 'Детские товары'),
        (5, 'Хэндмейд'),
        (6, 'Телефоны и планшеты'),
        (7, 'Фото и видеокамеры'),
        (8, 'Компьютерная техника'),
        (9, 'ТВ, аудио, видео'),
        (10, 'Бытовая техника'),
        (11, 'Для дома и дачи'),
        (12, 'Стройматериалы и инструменты'),
        (13, 'Красота и здоровье'),
        (14, 'Спорт и отдых'),
        (15, 'Хобби и развлечения'),
    )
    
    CONDITION = (
        (None, 'Не выбрано'),
        (0, 'БУ'),
        (1, 'Новое')
    )
    
    TYPE_ANNOUNCEMENT = (
        (None, 'Не выбрано'),
        (0, 'Продаю свое'),
        (1, 'Приобрел на продажу'),
        (2, 'Магазин'),
    )
    
    COMMUNICATION_METHOD = (
        (0, 'Адрес электронной почты'),
        (1, 'Имя пользователя телеграм'),
        (2, 'Номер телефона')
    )
    
    seller = models.ForeignKey(Seller, verbose_name="продавец", on_delete=models.CASCADE)
    category = models.IntegerField(verbose_name="категория", choices=CATEGORIES)
    condition = models.IntegerField(verbose_name="состояние", choices=CONDITION)
    type_announcement = models.IntegerField(verbose_name="тип объявления", choices=TYPE_ANNOUNCEMENT)
    name = models.CharField(verbose_name="название", max_length=50)
    price = models.DecimalField(verbose_name="цена", max_digits=13, decimal_places=2, validators=[MinValueValidator(0)])
    description = models.TextField(verbose_name="описание", max_length=3000, blank=True, null=True)
    sold = models.BooleanField(verbose_name="продано", default=False)
    latitude = models.FloatField(verbose_name="широта")
    longitude = models.FloatField(verbose_name="долгота")
    date_created = models.DateTimeField(verbose_name="дата создания", auto_now_add=True)
    date_updated = models.DateTimeField(verbose_name="дата изменения", auto_now_add=True)
    communication_method = models.IntegerField(verbose_name="способ связи", choices=COMMUNICATION_METHOD, default=0)
    
    class Meta:
        verbose_name = 'объявление'
        verbose_name_plural = 'объявления'
        ordering = ('-date_created', )
    
    def __str__(self):
        return self.name if len(self.name) <= 25 else f'{self.name[0:25]}...'


def _get_announcement_sale_image_filepath(self, image_name):
    return f'user_images/{self.announcement.seller.user.pk}/{self.announcement.pk}/{image_name}'


class AnnouncementImage(models.Model):
    announcement = models.ForeignKey(Announcement, verbose_name="объявление",  on_delete=models.CASCADE)
    image = models.ImageField(verbose_name="изображение", upload_to=_get_announcement_sale_image_filepath)
    
    class Meta:
        verbose_name = 'изображение объявления'
        verbose_name_plural = 'изображения объявлений'
    
    def __str__(self):
        return self.image.name.split('/')[-1]
    
    def delete(self):
        self.image.storage.delete(self.image.name)
        super().delete()

announcement/forms.py
from django import forms
from .models import Announcement


class AnnouncementCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].widget.attrs.update({'class': 'form-select form-control'})
        self.fields['condition'].widget.attrs.update({'class': 'form-select form-control'})
        self.fields['type_announcement'].widget.attrs.update({'class': 'form-select form-control'})
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['price'].widget.attrs.update({'class': 'form-control', 'max': 99999999999.99})
        self.fields['description'] = forms.CharField(label='Описание', max_length=3000, required=False, widget=forms.Textarea({'class': 'form-control', 'rows': 5}))

    latitude = forms.FloatField(
        label='Широта',
        required=True,
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'type': 'hidden'
        }))

    longitude = forms.FloatField(
        label='Долгота',
        required=True,
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'type': 'hidden'
        }))

    communication_method = forms.IntegerField(
        label='Способ связи',
        required=True,
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'type': 'hidden',
            'value': '0'
        }))

    class Meta:
        model = Announcement
        fields = ('category', 'condition', 'type_announcement', 'name', 'price', 'description', 'communication_method')

announcement/views.py
import os
import json
from sauto import settings
from django.http.response import JsonResponse
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from seller.forms import SellerCreationForm
from seller.utils import is_seller, validate_seller_data, get_or_create_seller, get_telegram_username_and_phone_number_from_data
from sauto.utils import validate_form_data, Response
from .forms import AnnouncementCreationForm
from .utils import validate_images, create_and_get_announcement, create_announcement_images, get_all_data_from_announcement_creation_page, validate_all_data_from_announcement_creation_page, get_contact_info, form_announcements_and_images, paginate_announcements, update_announcement_images, update_announcement
from .models import Announcement, Seller, AnnouncementImage


def announcements(request):
    announcements = Announcement.objects.filter(sold=False)
    categories = Announcement.CATEGORIES[1:]
    conditions = Announcement.CONDITION[1:]
    types_announcement = Announcement.TYPE_ANNOUNCEMENT[1:]
    communication_methods = Announcement.COMMUNICATION_METHOD
    if request.method == 'GET':
        if (request.GET.get('filter')
            or request.GET.get('search')
                or request.GET.get('all')):
            response = form_announcements_and_images(request, announcements)
            return JsonResponse(response._asdict())
    
    page_announcements, paginator = paginate_announcements(request, announcements)
    images = AnnouncementImage.objects.filter(
        announcement__in=page_announcements)
    
    context = {
        'announcements': page_announcements,
        'paginator': paginator,
        'images': images,
        'categories': categories,
        'conditions': conditions,
        'types_announcement': types_announcement,
        'communication_methods': communication_methods,
    }
    return render(request, 'announcement/announcements.html', context)


def show_announcement(request, announcement_pk: int):
    announcement = get_object_or_404(Announcement, pk=announcement_pk)
    seller = Seller.objects.get(pk=announcement.seller.pk)
    images = AnnouncementImage.objects.filter(announcement=announcement)
    if request.method == 'GET':
        if request.GET.get('show-contact-info'):
            response = get_contact_info(request, announcement)
            return JsonResponse(response._asdict())
    context = {
        'announcement': announcement,
        'seller': seller,
        'images': images,
        'yandex_map_api_key': settings.YANDEX_MAP_API_KEY,
    }
    return render(request, 'announcement/show-announcement.html', context)


@login_required
def add_announcement(request):
    form = AnnouncementCreationForm
    if request.method == 'POST':
        if request.POST.get('action') == 'add-announcement':
            data = get_all_data_from_announcement_creation_page(request)
            response = validate_all_data_from_announcement_creation_page(data)
            if response.status == 200:
                telegram_username, phone_number = get_telegram_username_and_phone_number_from_data(data['seller_data'])
                seller = get_or_create_seller(request, telegram_username, phone_number)
                announcement = create_and_get_announcement(seller, data)
                create_announcement_images(announcement, data)
                response = Response(
                    body={'success': 'Объявление добавлено.',
                          'url': request.build_absolute_uri(reverse('announcements'))},
                    type='redirect', status=200)
            return JsonResponse(response._asdict())
        elif request.POST.get('action') == 'validate-image':
            images = request.FILES
            response = validate_images(images)
            return JsonResponse(response._asdict())
        else:
            data = json.loads(request.body)
            if data['action'] == 'validate-announcement-data':
                form_data = AnnouncementCreationForm(data['formData'])
                response = validate_form_data(form_data=form_data)
                return JsonResponse(response._asdict())
            elif data['action'] == 'validate-seller-data':
                response = validate_seller_data(data=data['formData'])
                return JsonResponse(response._asdict())
    
    context = {
        'form': form,
        'yandex_map_api_key': settings.YANDEX_MAP_API_KEY,
    }
    
    if not is_seller(request.user):
        seller_form = SellerCreationForm
        context['seller_form'] = seller_form
        
    return render(request, 'announcement/add-announcement.html', context)


@login_required
def edit_announcement(request, announcement_pk):
    seller = get_object_or_404(Seller, user=request.user)
    announcement = get_object_or_404(Announcement, pk=announcement_pk, seller=seller)
    images = AnnouncementImage.objects.filter(announcement=announcement)
    form = AnnouncementCreationForm(instance=announcement)
    if request.method == 'POST':
        if request.POST.get('action') == 'edit-announcement':
            data = get_all_data_from_announcement_creation_page(request)
            response = validate_all_data_from_announcement_creation_page(data)
            if response.status == 200:
                update_announcement(announcement, data)
                update_announcement_images(announcement, data)
                response = Response(
                    body={'success': 'Объявление изменено.',
                          'url': request.build_absolute_uri(reverse('announcements'))},
                    type='redirect', status=200)
            return JsonResponse(response._asdict())
        elif request.POST.get('action') == 'validate-image':
            images = request.FILES
            response = validate_images(images)
            return JsonResponse(response._asdict())
        else:
            data = json.loads(request.body)
            if data['action'] == 'validate-announcement-data':
                form_data = AnnouncementCreationForm(data['formData'])
                response = validate_form_data(form_data=form_data)
                return JsonResponse(response._asdict())
        
    context = {
        'form': form,
        'announcement': announcement,
        'images': images,
        'yandex_map_api_key': settings.YANDEX_MAP_API_KEY,
    }
    return render(request, 'announcement/edit-announcement.html', context)


@login_required
def delete_announcement(request, announcement_pk):
    seller = get_object_or_404(Seller, user=request.user)
    announcement = get_object_or_404(Announcement, pk=announcement_pk, seller=seller)
    announcement_images = AnnouncementImage.objects.filter(announcement=announcement)
    dirname = os.path.dirname(announcement_images[0].image.path)
    for image in announcement_images:
        image.delete()
        
    os.rmdir(dirname)
    announcement.delete()
    response = Response(
        body={'success': 'Объявление удалено.'},
        type='OK', status=200)

    return JsonResponse(response._asdict())


@login_required
def change_sold_status_announcement(request, announcement_pk, status):
    seller = get_object_or_404(Seller, user=request.user)
    particle_not = ''
    if status == 'true':
        status = True
        particle_not = ''
    elif status == 'false':
        status = False
        particle_not = 'не '
        
    announcement = get_object_or_404(Announcement, pk=announcement_pk, seller=seller)
    announcement.sold = status
    announcement.save()
    response = Response(
        body={'success': f'Объявление отмечено как {particle_not}проданное.'},
        type='OK', status=200)

    return JsonResponse(response._asdict())

announcement/templates/announcement/announcement-card.html
<div class="col">
    <a href="{% url 'show-announcement' announcement.pk %}" class="text-decoration-none text-dark">
        <div class="card" style="overflow: hidden;">
            <div class="ratio">
                <div class="ratio-inner ratio-1-1">
                    <div class="ratio-content">
                        {% for image in images %}
                        {% if image.announcement == announcement %}
                        <img src="{{ image.image.url }}" class="img-100" alt="...">
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="card-body">
                {% if announcement.price == 0 %}
                <h5 class="card-title">Бесплатно</h5>
                {% else %}
                <h5 class="card-title">{{ announcement.price|floatformat:"-2g" }} ₽</h5>
                {% endif %}
                <div class="card-truncate-text-container">
                    <div class="card-truncate-text">
                        {{ announcement.name }}
                    </div>
                </div>
            </div>
        </div>
    </a>
</div>

announcement/templates/announcement/announcement-cards.html
{% load static %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xxl-4 g-4 mb-3" data-active-sold-status="">
    {% for announcement in announcements %}
    {% if request.user.id == announcement.seller.user.id %}
    {% include 'announcement/this-user-announcement-card.html' %}
    {% else %}
    {% include 'announcement/announcement-card.html' %}
    {% endif %}
    {% endfor %}
</div>

{% if paginator.num_pages > 1 %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">

        {% if announcements.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="First">
                <span aria-hidden="true">&#171;</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ announcements.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&#8249;</span>
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="First">
                <span aria-hidden="true">&#171;</span>
            </a>
        </li>
        <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&#8249;</span>
            </a>
        </li>
        {% endif %}

        {% for p in paginator.page_range %}
        {% if announcements.number == p %}
        <li class="page-item active"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
        {% elif p >= announcements.number|add:-2 and p <= announcements.number|add:2 %} <li class="page-item">
            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
            </li>
            {% endif %}
            {% endfor %}

            {% if announcements.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ announcements.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&#8250;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ announcements.paginator.num_pages }}" aria-label="Last">
                    <span aria-hidden="true">&#187;</span>
                </a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" aria-label="Next">
                    <span aria-hidden="true">&#8250;</span>
                </a>
            </li>
            <li class="page-item disabled">
                <a class="page-link" href="#" aria-label="Last">
                    <span aria-hidden="true">&#187;</span>
                </a>
            </li>
            {% endif %}

    </ul>
</nav>
{% endif %}

<div class="modal fade change-modal" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Удалить объявление?</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body change-input-div">
                Это действие невозможно отменить.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Отменить</button>
                <button type="submit" class="btn btn-outline-danger" data-href="" data-delete-announcement=""
                    data-bs-dismiss="modal">Удалить</button>
            </div>
        </div>
    </div>
</div>

<script class="delete-announcement-script"
    src="{% static 'js/announcement/delete-announcement/delete-announcement.js' %}"></script>
<script class="change-sold-status-announcement-script"
    src="{% static 'js/announcement/change-sold-status-announcement/change-sold-status-announcement.js' %}"></script>

announcement/templates/announcement/show-announcement.html
{% extends 'announcement/base.html' %}
{% load static %}
{% load favorite %}

{% block title %}{{ announcement.name }}{% endblock %}

{% block content %}
<script src="https://api-maps.yandex.ru/2.1/?apikey={{ yandex_map_api_key }}&lang=ru_RU" type="text/javascript"
    id="map-script"></script>
<link rel="stylesheet" href="{% static 'css/announcement/show-announcement.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css">

<div class="container my-5">
    <div class="row gx-5">
        <div class="col-12 col-lg-8 order-1 order-lg-0">
            <h4 class="mb-4 hidden">{{ announcement.name }}</h4>
            <div class="mb-4 img-container">
                <div class="swiper">
                    <div class="swiper-wrapper">
                        {% for image in images %}
                        <div class="swiper-slide">
                            <img src="{{ image.image.url }}" alt="...">
                        </div>
                        {% endfor %}
                    </div>
                    <div class="swiper-pagination"></div>
                    <div class="swiper-button-prev"></div>
                    <div class="swiper-button-next"></div>
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-12 col-md-3 col-lg-3 mb-2">
                    <span class="text-secondary">Описание</span>
                </div>
                <div class="col-12 col-md-9 col-lg-9 mb-3">
                    {{ announcement.description|linebreaksbr }}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-12 col-md-3 col-lg-3 mb-2">
                    <span class="text-secondary">Категория</span>
                </div>
                <div class="col-12 col-md-9 col-lg-9 mb-3">
                    {{ announcement.get_category_display }}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-12 col-md-3 col-lg-3 mb-2">
                    <span class="text-secondary">Состояние</span>
                </div>
                <div class="col-12 col-md-9 col-lg-9 mb-3">
                    {{ announcement.get_condition_display }}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-12 col-md-3 col-lg-3 mb-2">
                    <span class="text-secondary">Тип объявления</span>
                </div>
                <div class="col-12 col-md-9 col-lg-9 mb-3">
                    {{ announcement.get_type_announcement_display }}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-12 col-md-3 col-lg-3 mb-2">
                    <span class="text-secondary">Размещено</span>
                </div>
                <div class="col-12 col-md-9 col-lg-9 mb-3">
                    {{ announcement.date_created|date:"d b Y" }}
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-12 col-md-3 col-lg-3 mb-2">
                    <span class="text-secondary">Местоположение</span>
                </div>
                <div class="col-12 col-md-9 col-lg-9">
                    <div class="spinner-border text-secondary map-loader-spiner" role="status" style="display: flex;">
                        <span class="visually-hidden">Loading...</span>
                    </div>
                    <div class="mb-3" id="addressContainer"></div>
                    <div class="page-blackout fullscreen-map-container" style="display: none;">
                        <div id="loadedMap" class="fullscreen-map" data-latitude="{{ announcement.latitude }}"
                            data-longitude="{{ announcement.longitude }}"></div>
                        <button type="button" class="btn-close fullscreen-map-btn-close"></button>
                    </div>
                    <div class="show-map-container">
                        <div id="map" class="show-map-container-inner" data-latitude="{{ announcement.latitude }}"
                            data-longitude="{{ announcement.longitude }}">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-4 order-0 order-lg-1 mb-3 mb-lg-0">
            <div class="d-flex align-items-center justify-content-between mb-4">
                {% if announcement.price == 0 %}
                <h4 class="m-0">Бесплатно</h4>
                {% else %}
                <h4 class="m-0">{{ announcement.price|floatformat:"-2g" }} ₽</h4>
                {% endif %}
                <div class="d-flex ms-2" style="white-space: nowrap">
                    {% if not announcement|is_favorite:request.user %}
                    <button data-action="{% url 'add-favorite' announcement.pk %}" data-favorite-btn="1"
                        data-favorite-btn-type="add" class="btn-as-text text-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor"
                            class="bi bi-heart" viewBox="0 0 16 16">
                            <path
                                d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z" />
                        </svg>
                        <span class="ms-2">В избранное</span>
                    </button>
                    <button data-action="{% url 'remove-favorite' announcement.pk %}" data-favorite-btn="1"
                        data-favorite-btn-type="remove" class="btn-as-text text-primary" style="display: none;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor"
                            class="bi bi-heart-fill" viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z" />
                        </svg>
                        <span class="ms-2">В избранное</span>
                    </button>
                    {% else %}
                    <button data-action="{% url 'add-favorite' announcement.pk %}" data-favorite-btn="1"
                        data-favorite-btn-type="add" class="btn-as-text text-primary" style="display: none;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor"
                            class="bi bi-heart" viewBox="0 0 16 16">
                            <path
                                d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z" />
                        </svg>
                        <span class="ms-2">В избранное</span>
                    </button>
                    <button data-action="{% url 'remove-favorite' announcement.pk %}" data-favorite-btn="1"
                        data-favorite-btn-type="remove" class="btn-as-text text-primary">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor"
                            class="bi bi-heart-fill" viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z" />
                        </svg>
                        <span class="ms-2">В избранное</span>
                    </button>
                    {% endif %}
                </div>
            </div>
            <div class="d-grid mb-4">
                <button class="btn btn-primary" id="show-contact-info"
                    data-action="{% url 'show-announcement' announcement.pk %}">Показать контакт</button>
            </div>
            <a href="{% url 'user-announcements' seller.user.id %}" class="text-decoration-none">
                <div class="d-flex align-items-center px-2">
                    <div class="circle-image" style="width: 44px; height: 44px">
                        <img src="{{ seller.user.profile_image.url }}" alt="...">
                    </div>
                    <div class="flex-grow-1 ms-3">
                        <p class="m-0 mb-1 text-primary">{{ seller.user.first_name }} {{ seller.user.last_name }}</p>
                        <p class="m-0 text-dark">на Sauto с {{ seller.user.date_joined|date:"d b Y" }}</p>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
<script src="{% static 'js/announcement/show-announcement/image-slider.js' %}"></script>
<script src="{% static 'js/announcement/show-announcement/map.js' %}"></script>
<script src="{% static 'js/favorite/favorite.js' %}"></script>
<script src="{% static 'js/announcement/show-announcement/show-contact-info.js' %}"></script>
<script src="{% static 'js/announcement/show-announcement/fullscreen-map.js' %}"></script>
{% endblock %}